name: Lint, Test, and Deploy Prod H2O to AWS ECS

on:
  push:
    branches: [prod]


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: flake8
        run: |
          pip install `egrep -o 'flake8==\S+' web/requirements.txt`
          flake8 web/ --config web/setup.cfg
          flake8 docker/pandoc-lambda/function/ --config web/setup.cfg
      
      - name: black
        run: |
          pip install `egrep -o 'black==\S+' web/requirements.txt`
          black --check --diff .
      
      - name: mypy
        run: |
          cd web
          pip install -r requirements.txt
          PYTHONPATH=. mypy

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: docker compose up
        run: |
          docker ps -a
          docker compose logs

  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and tag image
        run: |
          docker build -t prod-h2o:latest .
          docker tag prod-h2o:latest prod-h2o:latest
      - name: Deploy info
        run: |
          echo "Deploying from: ${{ github.head_ref || github.ref_name }}"
          echo "Event type: ${{ github.event_name }}"