name: Lint, Test, and Deploy Pipeline
on:
  push:
    branches: [prod, staging, develop]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: flake8
        run: |
          pip install `egrep -o 'flake8==\S+' web/requirements.txt`
          flake8 web/ --config web/setup.cfg
          flake8 docker/pandoc-lambda/function/ --config web/setup.cfg
      
      - name: black
        run: |
          pip install `egrep -o 'black==\S+' web/requirements.txt`
          black --check --diff .
      
      - name: mypy
        run: |
          cd web
          pip install -r requirements.txt
          PYTHONPATH=. mypy

  test:
    runs-on: ubuntu-latest
    needs: lint  # This ensures test only runs after lint succeeds
    if: github.repository == 'shaban00/h2o'  # Don't run on forks
    steps:
      - uses: actions/checkout@v4
      - name: docker compose up
        run: |
          docker ps -a
          docker compose logs

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This ensures deploy only runs after test succeeds
    if: github.ref == 'refs/heads/staging'  # Only deploy staging branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and tag image
        run: |
          docker build -t staging-h2o:latest .
          docker tag staging-h2o:latest staging-h2o:latest