# don't fail the PR on coverage decrease
coverage:
  status:
    project: false
    patch: false
    changes: false

# rewrite paths so "main/models.py" becomes "_python/main/models.py" in coverage file:
fixes:
  - "::_python/"
